13 create a self contained distribution
belgif/rest-guide-validator pull request #33
Opened 2024-10-31 09:10 UTC by smals-mavh

Implemented CLI module.
Work on standalone / native compilation not yet started

2024-10-31 15:02 UTC, pvdbosch requested changes

2024-11-05 09:33 UTC, smals-mavh commented
Don't forget to make --files positional argument.

2024-11-05 14:33 UTC, smals-mavh commented on cli/pom.xml
> +                <version>3.3.1</version>
Did a pom cleanup

2024-11-05 14:38 UTC, smals-mavh commented on cli/src/test/java/io/github/belgif/rest/guide/validator/cli/BelgifRestGuideCliTest.java
> +        assertTrue(sw.toString().contains("For additional information: https://github.com/belgif/rest-guide-validator/blob/main/readme.md"));
Removed the footertest but kept the "Options" since this seems usefull to check if all options are automatically added by picocli?

2024-11-05 14:38 UTC, smals-mavh commented on cli/src/test/java/io/github/belgif/rest/guide/validator/cli/MyFirstTestCase.java
> +        File myFile = new File("C:/dev/prj/belgif/rest-guide-validator/integrationtest/src/it/externalReferencesFail/openapi.yaml");
Was an old test for debugging, removed

2024-11-05 15:46 UTC, pvdbosch approved these changes

2024-11-05 15:46 UTC, pvdbosch commented on pom.xml
> +        The belgif-rest-guide-validator Maven plugin is used to validate if an OpenAPI document conforms to the
you can remove "Maven plugin" here, we can document the choice between maven and cli in the README.MD

2024-11-05 15:46 UTC, pvdbosch commented on cli/src/main/java/io/github/belgif/rest/guide/validator/cli/BelgifRestGuideCli.java
> +        description = "The belgif-rest-guide-validator is used to validate if an OpenAPI document conforms to the guidelines in the Belgif REST guide.",
You can shorten to: "Validate if an OpenAPI document conforms to the guidelines in the Belgif REST guide."

2024-11-05 15:46 UTC, pvdbosch commented on cli/package/windows/main.wxs
> +<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
add xml comment that this file has been generated by command xyz + specify modifications

2024-11-06 08:18 UTC, pvdbosch commented on cli/src/main/java/io/github/belgif/rest/guide/validator/cli/options/ValidatorOptions.java
> +    @CommandLine.Option(names = {"-t", "--outputType"}, defaultValue = "console", description = "Output processors. For multiple values, repeat -t or --outputType. Options: CONSOLE, JUNIT, JSON, LOG4
default value is lowercase "console" while description specifies uppercase?

2024-11-07 09:23 UTC, merged